In [43]:
import torch
import torch.nn as nn
from torch import Tensor
import math

In [44]:
torch.manual_seed(40)
targets = torch.rand(4)
inputs = torch.rand(4)
targets, inputs

(tensor([0.3679, 0.8661, 0.1737, 0.7157]),
 tensor([0.8649, 0.4878, 0.5501, 0.1318]))

In [45]:
loss = nn.CrossEntropyLoss()

In [97]:
targets = torch.softmax(targets, dim=-1)
sum(inputs), sum(targets), inputs, targets

(tensor(2.0346),
 tensor(1.),
 tensor([0.8649, 0.4878, 0.5501, 0.1318]),
 tensor([0.2384, 0.2721, 0.2299, 0.2596]))

In [98]:
loss(input=inputs, target=targets)

tensor(1.4287)

In [99]:
losses = 0

for input, target in zip(inputs, targets):
    losses += math.log(input) * -target

losses

tensor(0.8933)

In [103]:
a = torch.randn(3, 5, requires_grad=True)
a

tensor([[ 2.0145, -0.7024,  1.2282,  1.0529,  0.1977],
        [ 0.1510, -0.0669,  1.0384,  0.2866,  0.9564],
        [-1.4264, -1.1770, -0.2615, -1.9677,  1.4340]], requires_grad=True)

In [104]:
b = torch.empty(3, dtype=torch.long).random_(5)
b

tensor([2, 0, 0])

In [107]:
out = loss(a, b)
print(out)
out.backward()

tensor(2.2337, grad_fn=<NllLossBackward0>)


In [132]:
x = Tensor([100, 95, 3, 2, 0, 0, 0, 0])
x

tensor([100.,  95.,   3.,   2.,   0.,   0.,   0.,   0.])

In [133]:
stdev, mean = torch.std_mean(x)
var = stdev**2
var

tensor(2005.4287)

In [134]:
y = Tensor([20, 25, 22, 30, 21, 27, 22, 25])
stdev, mean = torch.std_mean(y)
var = stdev**2
var

tensor(11.4286)