In [ ]:
import torch
import torch.nn as nn
from torch import Tensor

In [30]:
torch.manual_seed(11)

batch = 2
sqlen = 6
hidden_dim = 16
topk = 2

x = torch.randn(batch, sqlen, hidden_dim)
x_flat = x.view(-1, hidden_dim) # [12, 16]

def renormalization(input: Tensor) -> Tensor:
        total = input.sum(
            dim=-1, keepdim=True
        )  # total sum of experts' raw scores, not token count, hence -1 dim
        renormalized = input / total  # [batch*seqlen, topk]
        return renormalized

weights = renormalization(torch.rand(batch*sqlen, topk))
indices = torch.randint(0, 7, [batch*sqlen, topk])

weights, indices

(tensor([[0.5858, 0.4142],
         [0.4547, 0.5453],
         [0.7196, 0.2804],
         [0.7319, 0.2681],
         [0.5072, 0.4928],
         [0.5598, 0.4402],
         [0.2730, 0.7270],
         [0.4512, 0.5488],
         [0.1884, 0.8116],
         [0.3390, 0.6610],
         [0.0505, 0.9495],
         [0.8895, 0.1105]]),
 tensor([[3, 0],
         [1, 6],
         [4, 0],
         [2, 1],
         [1, 0],
         [3, 3],
         [4, 5],
         [3, 6],
         [6, 5],
         [4, 0],
         [0, 6],
         [4, 3]]))

In [31]:
# total weight being received
expert_load_0 = torch.where(indices==0)
token_idx, topk_idx = expert_load_0
token_idx, topk_idx

(tensor([ 0,  2,  4,  9, 10]), tensor([1, 1, 1, 1, 0]))

In [40]:
expert_0_weights_summed = sum([weights[i][j] for i, j in zip(token_idx, topk_idx)])
expert_0_weights_summed

tensor(1.8990)